### ISSUE TITLE
Fehler bei analysie einer selbst geschreibenen jar Datei

### ISSUE THREAD

**Issue by skyfly18** [sse-labs/fachproject-metrics-framework#34]
Der code als auch die jar Datei liegen im branch vdec. Der Name der jar Datei ist vdec-test-1.0.jar .
Der Fehler tritt auf wenn die Analysie mit dem Aufruf der SingleFileAnalysisApplication mit dem Pfad zur jar Datei gestartet wird.
Wird die jar Datei im Rahmen des Testest aufgerufen läuft alles ordnungsgemäß durch.
Der Fehler liegt nicht an der jar oder Opal Framework.

Ausgabe des Fehlers: 

java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "$this" is null
	at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:202)
	at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:198)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:302)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
	at scala.collection.mutable.ArrayOps$ofRef.filterImpl(ArrayOps.scala:198)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:395)
	at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:198)
	at org.tud.sse.metrics.opal.OPALProjectHelper$.getContainerFilesRecursive(OPALProjectHelper.scala:69)
	at org.tud.sse.metrics.opal.OPALProjectHelper$.jreClasses$lzycompute(OPALProjectHelper.scala:52)
	at org.tud.sse.metrics.opal.OPALProjectHelper$.jreClasses(OPALProjectHelper.scala:50)
	at org.tud.sse.metrics.opal.OPALProjectHelper$.buildOPALProject(OPALProjectHelper.scala:89)
	at org.tud.sse.metrics.application.SingleFileAnalysisApplication.$anonfun$calculateResults$3(SingleFileAnalysisApplication.scala:122)
	at scala.util.Try$.apply(Try.scala:213)
	at org.tud.sse.metrics.application.SingleFileAnalysisApplication.calculateResults(SingleFileAnalysisApplication.scala:115)
	at org.tud.sse.metrics.application.SingleFileAnalysisApplication.calculateResults$(SingleFileAnalysisApplication.scala:100)
	at org.tud.sse.metrics.impl.SingleFileAnalysisApplication$.calculateResults(SingleFileAnalysisApplication.scala:8)
	at org.tud.sse.metrics.application.FileAnalysisApplication.main(FileAnalysisApplication.scala:116)
	at org.tud.sse.metrics.application.FileAnalysisApplication.main$(FileAnalysisApplication.scala:108)
	at org.tud.sse.metrics.impl.SingleFileAnalysisApplication$.main(SingleFileAnalysisApplication.scala:8)
	at org.tud.sse.metrics.impl.SingleFileAnalysisApplication.main(SingleFileAnalysisApplication.scala)

**Comment by johannesduesing** [comment]
Ich bin mir noch nicht sicher ob ich das Problem richtig verstanden habe. Ich habe mir den aktuellen Stand aus dem Branch geholt. Der Test `NumberOfVariablesDeclaredTest` läuft bei mir durch, ebenfalls konnte ich die `NumberOfVariablesDeclaredAnalysis` in die `demo.DefaultSingleFileAnalysis` einhängen und ohne Probleme auf dem `vdec-test-1.0.jar` ausführen (in IntelliJ). 

Wann genau tritt der Fehler auf? In IntelliJ oder außerhalb davon? Und welche Kommandozeilen-Parameter wurden genutzt?

**Comment by skyfly18** [comment]
Nach mehren Versuche hab ich rausgefunden, dass das wohl ein bug in Intellij ist. Ich hab es auch geschafft das Programm laufen zulassen.
